version: '3.8'

services:
  node-app:
    build: .
    image: node-app
    ports:
      - '5000:5000'
    depends_on:
      - postgresdb
    volumes:
      - .:/usr/src/node-app
    env_file:
      - .env # Specify the path to your environment file
    networks:
      - node-network

  postgresdb:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - node-network

volumes:
  dbdata:
    driver: local

networks:
  node-network:
    driver: bridge
